SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200

-- Reiner Existenz-Check -- KEIN CREATE, KEIN ALTER, keine Aenderung an der DB.
-- Prueft fuer jede Tabelle aus der Sollliste fuer SVS41WH_FST
-- (laut FST_Tabellen.txt / Datei "check"), ob sie
--   a) bereits im Zielschema SVS41WH_FST existiert, und
--   b) in der Quelle SVS43WH_FST existiert (zum Klonen verfuegbar).
-- Gibt fuer jede Tabelle den Status aus. Keine Tabelle wird angelegt/geaendert.

DECLARE
  v_tgt_schema VARCHAR2(128) := 'SVS41WH_FST';
  v_src_schema VARCHAR2(128) := 'SVS43WH_FST';

  TYPE t_table_list IS TABLE OF VARCHAR2(128);
  v_tables t_table_list := t_table_list(
    'TD_DWH_ABRECHNUNG_LES02','TD_DWH_BEB_SCHULNAME','TD_DWH_BILDGUTSCHEIN','TD_DWH_COLIBRI_WBK',
    'TD_DWH_FST_BAK_ID','TD_DWH_FST_KTD_ID','TD_DWH_FST_PRS_ID','TD_DWH_FST_REHAFALL','TD_DWH_FST_ZSK_ID',
    'TD_DWH_GUT_EGG','TD_DWH_GUTSCHEIN','TD_DWH_MAG_FAKO','TD_DWH_MAG_KIBEKO','TD_DWH_MAG_WEIKO',
    'TD_DWH_MASSNAHME','TD_DWH_MASSNAHME_APS_PRAEMIE','TD_DWH_MASSNAHME_APS_ZUSCHUSS','TD_DWH_MASSNAHME_BNF_BETR',
    'TD_DWH_MASSNAHME_DFO','TD_DWH_MASSNAHME_FBW_SO','TD_DWH_MASSNAHME_GABE_BETRSTL','TD_DWH_MASSNAHME_GABE_ERH',
    'TD_DWH_MASSNAHME_MGBB_MBE','TD_DWH_MASSNAHME_MGBB_TBD','TD_DWH_MASSNAHME_QGE_AEH','TD_DWH_MAT_TNIL',
    'TD_DWH_MONAT_LETZTE12','TD_DWH_MONAT_1_BIS_11_VORM','TD_DWH_TEILNAHME','TD_DWH_TEILNAHME_AUW_BETRIEB',
    'TD_DWH_TEILNAHME_AUW_UNTERBR','TD_DWH_TEILNAHME_BNF_KOOP','TD_DWH_TEILNAHME_BOP','TD_DWH_TEILNAHME_DFZ',
    'TD_DWH_TEILNAHME_EVL_ABRZ','TD_DWH_TEILNAHME_EVL_ABRZ_MO','TD_DWH_TEILNAHME_EVL_COACH','TD_DWH_TEILNAHME_EVL_FZ',
    'TD_DWH_TEILNAHME_FBW_SOZ','TD_DWH_TEILNAHME_TAM_AFL','TD_DWH_TEILNAHME_TAM_COACH','TD_DWH_TEILNAHME_TAM_FZ',
    'TD_DWH_TEILNAHME_TAM_NB','TD_DWH_TEILNAHME_TAM_PR','TD_DWH_TEILNAHME_TAM_WB','TD_DWH_TEILNAHME_VB_LISTE',
    'TD_DWH_TEILNAHME_5P_LISTE','TD_DWH_TLN_EGS','TD_DWH_TRAEGERBETRIEB','TE_FST_AMDL_KURSNET',
    'TH_DWH_ABRECHNUNG_LES02','TH_DWH_ABRECHNUNG_LES03','TH_DWH_AFOEAN_FF','TH_DWH_AFOEAN_SWL',
    'TH_DWH_BEWA_ANGEB_FST','TH_DWH_BILDGUTSCHEIN','TH_DWH_BILDGUTSCHEIN_LBDAT','TH_DWH_BILDGUTSCHEIN_VH',
    'TH_DWH_COLIBRI_WBK','TH_DWH_DATUM_VORZEIT_BEENDET','TH_DWH_FESTLEGUNG_LES03','TH_DWH_FMZM_BH',
    'TH_DWH_FOERDERUNGEN_AVH','TH_DWH_FOERDERUNG_IVH','TH_DWH_FPEINZEL_PSA','TH_DWH_GUT_EGG','TH_DWH_GUTSCHEIN',
    'TH_DWH_GUTSCHEIN_AVGX','TH_DWH_GUTSCHEIN_AVG3','TH_DWH_GUTSCHEIN_GABE','TH_DWH_GUTSCHEIN_LBDAT',
    'TH_DWH_MASSNAHME','TH_DWH_MASSNAHME_AGH','TH_DWH_MASSNAHME_AGH_MONAT','TH_DWH_MASSNAHME_AGH_MONAT_TN',
    'TH_DWH_MASSNAHME_AGH_TAET','TH_DWH_MASSNAHME_APS_PRAEMIE','TH_DWH_MASSNAHME_APS_UNTG',
    'TH_DWH_MASSNAHME_APS_ZUSCHUSS','TH_DWH_MASSNAHME_ASA','TH_DWH_MASSNAHME_AUW','TH_DWH_MASSNAHME_AVG',
    'TH_DWH_MASSNAHME_BEB','TH_DWH_MASSNAHME_BNF','TH_DWH_MASSNAHME_BNF_BETR','TH_DWH_MASSNAHME_BOM',
    'TH_DWH_MASSNAHME_BVB','TH_DWH_MASSNAHME_EGF','TH_DWH_MASSNAHME_FBW','TH_DWH_MASSNAHME_FBWSA',
    'TH_DWH_MASSNAHME_FFSGB2','TH_DWH_MASSNAHME_FIM_BH','TH_DWH_MASSNAHME_FIM_VH','TH_DWH_MASSNAHME_FIN',
    'TH_DWH_MASSNAHME_GABE','TH_DWH_MASSNAHME_GABE_BETRSTL','TH_DWH_MASSNAHME_GABE_ERH',
    'TH_DWH_MASSNAHME_GABE_ZRBETRST','TH_DWH_MASSNAHME_GABE_1','TH_DWH_MASSNAHME_GAFA','TH_DWH_MASSNAHME_IRM',
    'TH_DWH_MASSNAHME_KEL','TH_DWH_MASSNAHME_LBDAT','TH_DWH_MASSNAHME_LES02','TH_DWH_MASSNAHME_MAT',
    'TH_DWH_MASSNAHME_MAT_ALT','TH_DWH_MASSNAHME_MAT08','TH_DWH_MASSNAHME_MGBB','TH_DWH_MASSNAHME_MGBB_MBE',
    'TH_DWH_MASSNAHME_MGBB_TBD','TH_DWH_MASSNAHME_PAM','TH_DWH_MASSNAHME_QGE','TH_DWH_MASSNAHME_QGE_AEH',
    'TH_DWH_MASSNAHME_TKM','TH_DWH_MASSNAHME_5PM','TH_DWH_MN_UNTERBR_ABM','TH_DWH_MODUL_LES02',
    'TH_DWH_MODUL_MNBEZ_BH','TH_DWH_PERS_BUDGET','TH_DWH_TEILNAHME','TH_DWH_TEILNAHME_ABR_KOST',
    'TH_DWH_TEILNAHME_AGH','TH_DWH_TEILNAHME_AH','TH_DWH_TEILNAHME_ANZ_BOM','TH_DWH_TEILNAHME_ANZ_PAM',
    'TH_DWH_TEILNAHME_ASA','TH_DWH_TEILNAHME_ASA_BEGLST','TH_DWH_TEILNAHME_AUW','TH_DWH_TEILNAHME_AUW_BERUF',
    'TH_DWH_TEILNAHME_AUW_BETRIEB','TH_DWH_TEILNAHME_AUW_MB','TH_DWH_TEILNAHME_AUW_UNTERBR',
    'TH_DWH_TEILNAHME_AVGX','TH_DWH_TEILNAHME_BEB','TH_DWH_TEILNAHME_BEH','TH_DWH_TEILNAHME_BNF',
    'TH_DWH_TEILNAHME_BNF_KOOP','TH_DWH_TEILNAHME_BOP','TH_DWH_TEILNAHME_BUAB','TH_DWH_TEILNAHME_BUEBO',
    'TH_DWH_TEILNAHME_BVB','TH_DWH_TEILNAHME_EGF','TH_DWH_TEILNAHME_EGF_FOERD','TH_DWH_TEILNAHME_ESFLZA',
    'TH_DWH_TEILNAHME_ESG','TH_DWH_TEILNAHME_ESG_KALK','TH_DWH_TEILNAHME_ESG_MIG','TH_DWH_TEILNAHME_EVL',
    'TH_DWH_TEILNAHME_EVL_ABRZ','TH_DWH_TEILNAHME_EVL_ABRZ_MO','TH_DWH_TEILNAHME_EVL_COACH',
    'TH_DWH_TEILNAHME_EVL_FZ','TH_DWH_TEILNAHME_EXG','TH_DWH_TEILNAHME_FAKO','TH_DWH_TEILNAHME_FAV',
    'TH_DWH_TEILNAHME_FBW','TH_DWH_TEILNAHME_FBWSA','TH_DWH_TEILNAHME_FFSGB2','TH_DWH_TEILNAHME_FIM_VH',
    'TH_DWH_TEILNAHME_GABE_1','TH_DWH_TEILNAHME_GABE_2','TH_DWH_TEILNAHME_GABE_3','TH_DWH_TEILNAHME_GAFA',
    'TH_DWH_TEILNAHME_IRM','TH_DWH_TEILNAHME_JOBCO','TH_DWH_TEILNAHME_KEL','TH_DWH_TEILNAHME_KIBEKO',
    'TH_DWH_TEILNAHME_LBDAT','TH_DWH_TEILNAHME_LES02','TH_DWH_TEILNAHME_LES03','TH_DWH_TEILNAHME_MAG',
    'TH_DWH_TEILNAHME_MAG_WEIKO','TH_DWH_TEILNAHME_MAT','TH_DWH_TEILNAHME_MAT08','TH_DWH_TEILNAHME_PB',
    'TH_DWH_TEILNAHME_QGE','TH_DWH_TEILNAHME_REHAEF','TH_DWH_TEILNAHME_REHAPRO','TH_DWH_TEILNAHME_SOT',
    'TH_DWH_TEILNAHME_TAM','TH_DWH_TEILNAHME_TAM_AFL','TH_DWH_TEILNAHME_TAM_COACH','TH_DWH_TEILNAHME_TAM_FZ',
    'TH_DWH_TEILNAHME_TAM_NB','TH_DWH_TEILNAHME_TAM_PR','TH_DWH_TEILNAHME_TAM_WB','TH_DWH_TEILNAHME_TNIL',
    'TH_DWH_TEILNAHME_VB','TH_DWH_TEILNAHME_VB_LISTE','TH_DWH_TEILNAHME_5P_LISTE','TH_DWH_TEILNAHME_5PT',
    'TH_DWH_TLN_EGS','TH_DWH_TN_UNTERBR_ABM','TH_DWH_TRAEGER','TH_DWH_TRAEGERBETRIEB','TH_DWH_TRAEGER_FBW',
    'TH_DWH_TRAEGER_INIT','TM_DWH_FST_LLZ','TR_DWH_FST_EVLCOACH_MGBB','TR_DWH_FST_TAAMCOACH_MGBB',
    'TR_DWH_FST_TBG','TR_DWH_FST_TR_BTR_BKD','TR_DWH_TLN_PERSB','TR_DWH_VORMN_PSA','TR_FST_COSACH_COLIBRI',
    'TT_DWH_FST_PROT_GS','TT_DWH_FST_PROT_MN','TT_DWH_FST_PROT_TN','TT_DWH_MASSNAHME','TT_FST_BAK_ID'
  );

  v_in_target PLS_INTEGER;
  v_in_source PLS_INTEGER;

  v_ok_cnt      PLS_INTEGER := 0;
  v_missing_cnt PLS_INTEGER := 0;
  v_nosrc_cnt   PLS_INTEGER := 0;

BEGIN
  FOR i IN 1 .. v_tables.COUNT LOOP

    SELECT COUNT(*) INTO v_in_target
    FROM dba_tables
    WHERE owner = v_tgt_schema AND table_name = v_tables(i);

    SELECT COUNT(*) INTO v_in_source
    FROM dba_tables
    WHERE owner = v_src_schema AND table_name = v_tables(i);

    IF v_in_target > 0 THEN
      DBMS_OUTPUT.PUT_LINE('OK (existiert bereits im Ziel):      ' || v_tgt_schema || '.' || v_tables(i));
      v_ok_cnt := v_ok_cnt + 1;
    ELSIF v_in_source > 0 THEN
      DBMS_OUTPUT.PUT_LINE('FEHLT IM ZIEL (in Quelle vorhanden): ' || v_tables(i));
      v_missing_cnt := v_missing_cnt + 1;
    ELSE
      DBMS_OUTPUT.PUT_LINE('NICHT GEFUNDEN (weder Ziel noch Quelle): ' || v_tables(i));
      v_nosrc_cnt := v_nosrc_cnt + 1;
    END IF;

  END LOOP;

  DBMS_OUTPUT.PUT_LINE('=================================================');
  DBMS_OUTPUT.PUT_LINE('Geprueft: ' || v_tables.COUNT
                        || '  |  Im Ziel vorhanden: ' || v_ok_cnt
                        || '  |  Fehlt im Ziel (Quelle vorhanden): ' || v_missing_cnt
                        || '  |  Nirgends gefunden: ' || v_nosrc_cnt);
  DBMS_OUTPUT.PUT_LINE('(Reiner Lesezugriff -- keine Tabelle wurde angelegt oder geaendert.)');
END;
/
