-- Prueft die 5 Schemata mit BEKANNTER Sollliste (aus FST_Tabellen.txt bzw.
-- der Datei "check") direkt: ist jede EXPLIZIT geforderte Tabelle im
-- Zielschema angelegt -- JA oder NEIN. Reiner Lesezugriff.
--
-- Wichtig, warum das ein separater Check ist (anders als
-- gesamtuebersicht_vor_datenladen.sql): dort wird die Tabellenmenge aus
-- Ziel UNION Quelle gebildet -- eine geforderte Tabelle, die WEDER im
-- Ziel NOCH in der Quelle existiert, wuerde dort gar nicht erst auftauchen.
-- Hier wird stattdessen die tatsaechliche Sollliste selbst durchgegangen,
-- so dass so ein Fall als "NEIN, nirgends gefunden" sichtbar wird.
--
-- Ergebnis ist EINE Tabelle (Result-Grid) -> direkt als CSV exportieren.

WITH
soll_tabellen (ziel_schema, table_name) AS (

  -- ===== SVS41WH_FST (211 Tabellen laut FST_Tabellen.txt) =====
  SELECT 'SVS41WH_FST', column_value FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'TD_DWH_ABRECHNUNG_LES02','TD_DWH_BEB_SCHULNAME','TD_DWH_BILDGUTSCHEIN','TD_DWH_COLIBRI_WBK',
    'TD_DWH_FST_BAK_ID','TD_DWH_FST_KTD_ID','TD_DWH_FST_PRS_ID','TD_DWH_FST_REHAFALL','TD_DWH_FST_ZSK_ID',
    'TD_DWH_GUT_EGG','TD_DWH_GUTSCHEIN','TD_DWH_MAG_FAKO','TD_DWH_MAG_KIBEKO','TD_DWH_MAG_WEIKO',
    'TD_DWH_MASSNAHME','TD_DWH_MASSNAHME_APS_PRAEMIE','TD_DWH_MASSNAHME_APS_ZUSCHUSS','TD_DWH_MASSNAHME_BNF_BETR',
    'TD_DWH_MASSNAHME_DFO','TD_DWH_MASSNAHME_FBW_SO','TD_DWH_MASSNAHME_GABE_BETRSTL','TD_DWH_MASSNAHME_GABE_ERH',
    'TD_DWH_MASSNAHME_MGBB_MBE','TD_DWH_MASSNAHME_MGBB_TBD','TD_DWH_MASSNAHME_QGE_AEH','TD_DWH_MAT_TNIL',
    'TD_DWH_MONAT_LETZTE12','TD_DWH_MONAT_1_BIS_11_VORM','TD_DWH_TEILNAHME','TD_DWH_TEILNAHME_AUW_BETRIEB',
    'TD_DWH_TEILNAHME_AUW_UNTERBR','TD_DWH_TEILNAHME_BNF_KOOP','TD_DWH_TEILNAHME_BOP','TD_DWH_TEILNAHME_DFZ',
    'TD_DWH_TEILNAHME_EVL_ABRZ','TD_DWH_TEILNAHME_EVL_ABRZ_MO','TD_DWH_TEILNAHME_EVL_COACH','TD_DWH_TEILNAHME_EVL_FZ',
    'TD_DWH_TEILNAHME_FBW_SOZ','TD_DWH_TEILNAHME_TAM_AFL','TD_DWH_TEILNAHME_TAM_COACH','TD_DWH_TEILNAHME_TAM_FZ',
    'TD_DWH_TEILNAHME_TAM_NB','TD_DWH_TEILNAHME_TAM_PR','TD_DWH_TEILNAHME_TAM_WB','TD_DWH_TEILNAHME_VB_LISTE',
    'TD_DWH_TEILNAHME_5P_LISTE','TD_DWH_TLN_EGS','TD_DWH_TRAEGERBETRIEB','TE_FST_AMDL_KURSNET',
    'TH_DWH_ABRECHNUNG_LES02','TH_DWH_ABRECHNUNG_LES03','TH_DWH_AFOEAN_FF','TH_DWH_AFOEAN_SWL',
    'TH_DWH_BEWA_ANGEB_FST','TH_DWH_BILDGUTSCHEIN','TH_DWH_BILDGUTSCHEIN_LBDAT','TH_DWH_BILDGUTSCHEIN_VH',
    'TH_DWH_COLIBRI_WBK','TH_DWH_DATUM_VORZEIT_BEENDET','TH_DWH_FESTLEGUNG_LES03','TH_DWH_FMZM_BH',
    'TH_DWH_FOERDERUNGEN_AVH','TH_DWH_FOERDERUNG_IVH','TH_DWH_FPEINZEL_PSA','TH_DWH_GUT_EGG','TH_DWH_GUTSCHEIN',
    'TH_DWH_GUTSCHEIN_AVGX','TH_DWH_GUTSCHEIN_AVG3','TH_DWH_GUTSCHEIN_GABE','TH_DWH_GUTSCHEIN_LBDAT',
    'TH_DWH_MASSNAHME','TH_DWH_MASSNAHME_AGH','TH_DWH_MASSNAHME_AGH_MONAT','TH_DWH_MASSNAHME_AGH_MONAT_TN',
    'TH_DWH_MASSNAHME_AGH_TAET','TH_DWH_MASSNAHME_APS_PRAEMIE','TH_DWH_MASSNAHME_APS_UNTG',
    'TH_DWH_MASSNAHME_APS_ZUSCHUSS','TH_DWH_MASSNAHME_ASA','TH_DWH_MASSNAHME_AUW','TH_DWH_MASSNAHME_AVG',
    'TH_DWH_MASSNAHME_BEB','TH_DWH_MASSNAHME_BNF','TH_DWH_MASSNAHME_BNF_BETR','TH_DWH_MASSNAHME_BOM',
    'TH_DWH_MASSNAHME_BVB','TH_DWH_MASSNAHME_EGF','TH_DWH_MASSNAHME_FBW','TH_DWH_MASSNAHME_FBWSA',
    'TH_DWH_MASSNAHME_FFSGB2','TH_DWH_MASSNAHME_FIM_BH','TH_DWH_MASSNAHME_FIM_VH','TH_DWH_MASSNAHME_FIN',
    'TH_DWH_MASSNAHME_GABE','TH_DWH_MASSNAHME_GABE_BETRSTL','TH_DWH_MASSNAHME_GABE_ERH',
    'TH_DWH_MASSNAHME_GABE_ZRBETRST','TH_DWH_MASSNAHME_GABE_1','TH_DWH_MASSNAHME_GAFA','TH_DWH_MASSNAHME_IRM',
    'TH_DWH_MASSNAHME_KEL','TH_DWH_MASSNAHME_LBDAT','TH_DWH_MASSNAHME_LES02','TH_DWH_MASSNAHME_MAT',
    'TH_DWH_MASSNAHME_MAT_ALT','TH_DWH_MASSNAHME_MAT08','TH_DWH_MASSNAHME_MGBB','TH_DWH_MASSNAHME_MGBB_MBE',
    'TH_DWH_MASSNAHME_MGBB_TBD','TH_DWH_MASSNAHME_PAM','TH_DWH_MASSNAHME_QGE','TH_DWH_MASSNAHME_QGE_AEH',
    'TH_DWH_MASSNAHME_TKM','TH_DWH_MASSNAHME_5PM','TH_DWH_MN_UNTERBR_ABM','TH_DWH_MODUL_LES02',
    'TH_DWH_MODUL_MNBEZ_BH','TH_DWH_PERS_BUDGET','TH_DWH_TEILNAHME','TH_DWH_TEILNAHME_ABR_KOST',
    'TH_DWH_TEILNAHME_AGH','TH_DWH_TEILNAHME_AH','TH_DWH_TEILNAHME_ANZ_BOM','TH_DWH_TEILNAHME_ANZ_PAM',
    'TH_DWH_TEILNAHME_ASA','TH_DWH_TEILNAHME_ASA_BEGLST','TH_DWH_TEILNAHME_AUW','TH_DWH_TEILNAHME_AUW_BERUF',
    'TH_DWH_TEILNAHME_AUW_BETRIEB','TH_DWH_TEILNAHME_AUW_MB','TH_DWH_TEILNAHME_AUW_UNTERBR',
    'TH_DWH_TEILNAHME_AVGX','TH_DWH_TEILNAHME_BEB','TH_DWH_TEILNAHME_BEH','TH_DWH_TEILNAHME_BNF',
    'TH_DWH_TEILNAHME_BNF_KOOP','TH_DWH_TEILNAHME_BOP','TH_DWH_TEILNAHME_BUAB','TH_DWH_TEILNAHME_BUEBO',
    'TH_DWH_TEILNAHME_BVB','TH_DWH_TEILNAHME_EGF','TH_DWH_TEILNAHME_EGF_FOERD','TH_DWH_TEILNAHME_ESFLZA',
    'TH_DWH_TEILNAHME_ESG','TH_DWH_TEILNAHME_ESG_KALK','TH_DWH_TEILNAHME_ESG_MIG','TH_DWH_TEILNAHME_EVL',
    'TH_DWH_TEILNAHME_EVL_ABRZ','TH_DWH_TEILNAHME_EVL_ABRZ_MO','TH_DWH_TEILNAHME_EVL_COACH',
    'TH_DWH_TEILNAHME_EVL_FZ','TH_DWH_TEILNAHME_EXG','TH_DWH_TEILNAHME_FAKO','TH_DWH_TEILNAHME_FAV',
    'TH_DWH_TEILNAHME_FBW','TH_DWH_TEILNAHME_FBWSA','TH_DWH_TEILNAHME_FFSGB2','TH_DWH_TEILNAHME_FIM_VH',
    'TH_DWH_TEILNAHME_GABE_1','TH_DWH_TEILNAHME_GABE_2','TH_DWH_TEILNAHME_GABE_3','TH_DWH_TEILNAHME_GAFA',
    'TH_DWH_TEILNAHME_IRM','TH_DWH_TEILNAHME_JOBCO','TH_DWH_TEILNAHME_KEL','TH_DWH_TEILNAHME_KIBEKO',
    'TH_DWH_TEILNAHME_LBDAT','TH_DWH_TEILNAHME_LES02','TH_DWH_TEILNAHME_LES03','TH_DWH_TEILNAHME_MAG',
    'TH_DWH_TEILNAHME_MAG_WEIKO','TH_DWH_TEILNAHME_MAT','TH_DWH_TEILNAHME_MAT08','TH_DWH_TEILNAHME_PB',
    'TH_DWH_TEILNAHME_QGE','TH_DWH_TEILNAHME_REHAEF','TH_DWH_TEILNAHME_REHAPRO','TH_DWH_TEILNAHME_SOT',
    'TH_DWH_TEILNAHME_TAM','TH_DWH_TEILNAHME_TAM_AFL','TH_DWH_TEILNAHME_TAM_COACH','TH_DWH_TEILNAHME_TAM_FZ',
    'TH_DWH_TEILNAHME_TAM_NB','TH_DWH_TEILNAHME_TAM_PR','TH_DWH_TEILNAHME_TAM_WB','TH_DWH_TEILNAHME_TNIL',
    'TH_DWH_TEILNAHME_VB','TH_DWH_TEILNAHME_VB_LISTE','TH_DWH_TEILNAHME_5P_LISTE','TH_DWH_TEILNAHME_5PT',
    'TH_DWH_TLN_EGS','TH_DWH_TN_UNTERBR_ABM','TH_DWH_TRAEGER','TH_DWH_TRAEGERBETRIEB','TH_DWH_TRAEGER_FBW',
    'TH_DWH_TRAEGER_INIT','TM_DWH_FST_LLZ','TR_DWH_FST_EVLCOACH_MGBB','TR_DWH_FST_TAAMCOACH_MGBB',
    'TR_DWH_FST_TBG','TR_DWH_FST_TR_BTR_BKD','TR_DWH_TLN_PERSB','TR_DWH_VORMN_PSA','TR_FST_COSACH_COLIBRI',
    'TT_DWH_FST_PROT_GS','TT_DWH_FST_PROT_MN','TT_DWH_FST_PROT_TN','TT_DWH_MASSNAHME','TT_FST_BAK_ID'
  ))

  UNION ALL

  -- ===== SVS41WH_BA_TRS (16 Tabellen) =====
  SELECT 'SVS41WH_BA_TRS', column_value FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'TD_DWH_BETRIEB','TD_DWH_TRAEGER','TE_FST_AMDL_KURSNET_TRS','TH_DWH_COLIBRI_WBK_TRS',
    'TH_DWH_MASSNAHME_AGH_TAET_TRS','TH_DWH_MASSNAHME_AUW_TRS','TH_DWH_MASSNAHME_BNF_TRS',
    'TH_DWH_MASSNAHME_DFO_TRS','TH_DWH_MASSNAHME_EGF_TRS','TH_DWH_MASSNAHME_FBW_SO_TRS',
    'TH_DWH_MASSNAHME_TRS','TH_DWH_MASSNAHME_VRTG','TH_DWH_TRAEGERBETRIEB_TRS',
    'TH_DWH_TRAEGER_FBW_TRS','TH_DWH_TRAEGER_INIT_TRS','TH_DWH_TRAEGER_TRS'
  ))

  UNION ALL

  -- ===== SVS41WH_STAT_FST (68 Tabellen) =====
  SELECT 'SVS41WH_STAT_FST', column_value FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'TD_FST_KAG','TD_FST_KBD','TD_FST_KFT','TD_FST_KGS','TD_FST_KMN','TD_FST_KSG','TD_KONS_TRAEGER',
    'TH_FST_KAG_B','TH_FST_KAG_B_S','TH_FST_KAG_E','TH_FST_KAG_V','TH_FST_KBD_B','TH_FST_KBD_B_S',
    'TH_FST_KBD_E','TH_FST_KBD_V','TH_FST_KFT_B','TH_FST_KFT_B_S','TH_FST_KFT_B_Z','TH_FST_KFT_E',
    'TH_FST_KFT_V','TH_FST_KGS_B','TH_FST_KGS_B_S','TH_FST_KGS_E','TH_FST_KGS_V','TH_FST_KMN_B',
    'TH_FST_KMN_B_S','TH_FST_KMN_E','TH_FST_KMN_V','TH_FST_KSG_B','TH_FST_KSG_B_S','TH_FST_KSG_E',
    'TH_FST_KSG_V','TR_DWH_KTR_BTR','TR_DWH_KTR_TBR','TT_DWH_AAW_APP','TT_DWH_ADW_APP','TT_DWH_AGW_APP',
    'TT_DWH_ASW_APP','TT_DWH_AUW_APP','TT_DWH_BAW_APP','TT_DWH_BDW_APP','TT_DWH_BGW_APP','TT_DWH_BSW_APP',
    'TT_DWH_BUW_APP','TT_DWH_FAY_APP','TT_DWH_FDY_APP','TT_DWH_FGY_APP','TT_DWH_FSY_APP','TT_DWH_FUY_APP',
    'TT_DWH_GAQ_APP','TT_DWH_GDQ_APP','TT_DWH_GGQ_APP','TT_DWH_GSQ_APP','TT_DWH_GUQ_APP','TT_DWH_MAY_APP',
    'TT_DWH_MDY_APP','TT_DWH_MGY_APP','TT_DWH_MSY_APP','TT_DWH_MUY_APP','TT_DWH_SAQ_APP','TT_DWH_SDQ_APP',
    'TT_DWH_SGQ_APP','TT_DWH_SSQ_APP','TT_DWH_SUQ_APP','TT_FST_FBV_GG_APP','TT_FST_GS_MAP_3',
    'TT_FST_GS_MAP_5','TT_FST_KONSH_PROT','TT_FST_KTW'
  ))

  UNION ALL

  -- ===== SVS41WH_STAT_BA_TRS (1 Tabelle) =====
  SELECT 'SVS41WH_STAT_BA_TRS', column_value FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'TT_DWH_DFO_STRNR'
  ))

  UNION ALL

  -- ===== SVS41M_STAT_FST (101 Tabellen) =====
  SELECT 'SVS41M_STAT_FST', column_value FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'TF_FST_BD_KERN','TF_FST_DIM_BST','TF_FST_DIM_LST','TF_FST_EGG','TF_FST_GS_KERN',
    'TF_FST_KGS','TF_FST_KOH_VERBL','TF_FST_MN_ABM','TF_FST_MN_AGH','TF_FST_MN_APS_BETRIEB',
    'TF_FST_MN_APS_BETRIEB_2','TF_FST_MN_APS_BETRIEB_3','TF_FST_MN_APS_PRAEMIE','TF_FST_MN_APS_ZUSCHUSS',
    'TF_FST_MN_AUW','TF_FST_MN_BEB','TF_FST_MN_BNF','TF_FST_MN_BOM','TF_FST_MN_BVB','TF_FST_MN_EMM',
    'TF_FST_MN_FBW','TF_FST_MN_FFSGB2','TF_FST_MN_FIM','TF_FST_MN_GAFA','TF_FST_MN_IRM','TF_FST_MN_ISM',
    'TF_FST_MN_KEL','TF_FST_MN_KERN','TF_FST_MN_LES','TF_FST_MN_MABE','TF_FST_MN_PSA','TF_FST_MN_P37',
    'TF_FST_RE_KERN','TF_FST_TN_ABM','TF_FST_TN_AFLJP','TF_FST_TN_AGH','TF_FST_TN_AH','TF_FST_TN_ASA',
    'TF_FST_TN_AUW','TF_FST_TN_BEB','TF_FST_TN_BEH','TF_FST_TN_BNF','TF_FST_TN_BNF_KORR','TF_FST_TN_BOM',
    'TF_FST_TN_BVB','TF_FST_TN_EGF','TF_FST_TN_EGS','TF_FST_TN_EMM','TF_FST_TN_ESFLZA','TF_FST_TN_ESG',
    'TF_FST_TN_EVL','TF_FST_TN_EXG','TF_FST_TN_FAV','TF_FST_TN_FBW','TF_FST_TN_FF','TF_FST_TN_FFSGB2',
    'TF_FST_TN_FIM','TF_FST_TN_GABE','TF_FST_TN_GAFA','TF_FST_TN_IRM','TF_FST_TN_ISM','TF_FST_TN_KEL',
    'TF_FST_TN_KERN','TF_FST_TN_LES','TF_FST_TN_MABE','TF_FST_TN_MIGHIN','TF_FST_TN_PB','TF_FST_TN_PSA',
    'TF_FST_TN_P37','TF_FST_TN_REHAEF','TF_FST_TN_REHAPRO','TF_FST_TN_SOT','TF_FST_TN_SWL','TF_FST_TN_TAM',
    'TF_FST_TN_VB','TF_FST_TN_VGS','TF_FST_TN_5P','TF_FST_TR_ABM','TF_FST_TR_AFLJP','TF_FST_TR_EMM',
    'TF_FST_TR_FF','TF_FST_TR_ISM','TF_FST_TR_KERN','TF_FST_TR_PSA','TF_FST_TR_P37','TF_FST_TR_SWL',
    'TF_FST_TR_VGS','TF_REHA_SB_VORGAENGE','TG_FST_HOCH_TLN','TG_FST_P48PRS','TT_DM_FST_GEBKONS_STAT',
    'TT_FST_FESTSCHR_AL','TT_FST_FESTSCHR_BGS','TT_FST_FESTSCHR_GS','TT_FST_FESTSCHR_MN','TT_FST_FESTSCHR_PRS',
    'TT_FST_FESTSCHR_RE','TT_FST_FESTSCHR_TN','TT_FST_LST_EIN','TT_FST_RE_ERSTE_FOERD','TT_FST_REGZENS'
  ))

)
SELECT
  st.ziel_schema,
  st.table_name,
  CASE WHEN tgt.table_name IS NOT NULL THEN 'JA' ELSE 'NEIN' END AS erstellt_im_ziel
FROM soll_tabellen st
LEFT JOIN dba_tables tgt
       ON tgt.owner = st.ziel_schema AND tgt.table_name = st.table_name
ORDER BY st.ziel_schema, st.table_name;
